#!/bin/python3

import math
import os
import random
import re
import sys

from collections import defaultdict

#
# Complete the 'cutTheSticks' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#
#  def cut_sticks(sticks):
#  	count = 0
#  	if sticks:
#  		small_stick = min(sticks)
#  	else:
#  		return
#  	new_sticks = []
#  	for element in sticks:
#  		count = count + 1
#  		new_element = element - small_stick
#  		if new_element != 0:
#  			new_sticks.append(new_element)
#  	print count 
#  	cut_sticks(new_sticks)

def cutTheSticks(arr):
    d = defaultdict(int)
    for a in arr:
        d[a] += 1
    d = sorted(list(d.items()))
    res = [len(arr)]
    for _, n in d[:-1]:
        res.append(res[-1] - n)
    return res
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
