#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the flatlandSpaceStations function below.
def flatlandSpaceStations(n, stations):
    stations = sorted(stations)
    res = stations[0]
    
    for ind in range(1, len(stations)):
        res = max(res, (stations[ind] - stations[ind-1])//2)
        
    res = max(res, n-1 - stations[-1])
        
    return res

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    c = list(map(int, input().rstrip().split()))

    result = flatlandSpaceStations(n, c)

    fptr.write(str(result) + '\n')

    fptr.close()
